### ISSUE TITLE
fetchs repositories with a regular expression

### ISSUE THREAD

**Issue by hugolesta** [felipem1210/GitHelper#6]
As a user that wants to clone multiple repositories from our documentation, I want to fetch all the repositories that start with the word terraform-, so that, probably search by a regular expression might be useful to achieve that.

**Comment by felipem1210** [comment]
To achieve this I will add the option to get repo info based on regular expression

**Comment by felipem1210** [comment]
Added in https://github.com/felipem1210/git-helper/releases/tag/v0.2.0
